### PR TITLE
Minor Updates and support for modern cmake targets

### PR DESCRIPTION
**Pull request by ShaddyDC**
I've tried to use this together with vcpkg on windows, and ran across some issues and warnings. I also added target support that allows you to import the library comfortably (with vcpkg, at least). I don't think I broke anything, but I'm open to discuss any changes and rework them.

### CODE REVIEW

**Comment by lecopivo** [comment]
Thanks a lot for the contribution and for the clean up, the repository is a bit of a mess right now :/

You are using the most up to date Magnum v2018.04, right? Right now, I have installed v2018.02 which does not have the GL module. I have to upgrade to v2018.04, this might take me a while since my other projects work with v2018.02.

Btw, I'm still not sure if this repository should download and build `ImGui` itself or not. What do you think?

**Comment by ShaddyDC** [comment]
Yeah, I'm using a fairly recent version. I hadn't really considered that adding that stuff might break some compatibility, but it definitely makes sense. Take your time with updating your stuff. I've also made your current version work with vcpkg package manager and will probably try to add it there as well. These changes would just make adapting future versions easier for me, so there's no rush at all at the moment. :)

Imgui is also available in vcpkg, so for me personally it's fairly comfortable to already have it available and just import it with a find_package call. That solution probably doesn't work in most circumstances though since the imgui targets are unique to the vcpkg port. Maybe it's possible to detect if the library is currently being built with vcpkg and only try to find the package that way then and otherwise use the find_library solution. I'll look into that if I find the opportunity.
So yeah, for me personally it's definitely more convenient to have imgui externally, but I can see that that can be quite different for other people. Maybe add a build option if we can't come to a conclusion. It wouldn't really be hard to make it download only if the user asks for it.

**Comment by lecopivo** [comment]
Thanks for the changes once again!

Also thanks for bringing vcpkg to my attention, a month ago it was ported to Linux and so far I really like it. With a slight modification to how Corrade and Magnum is build on Linux I have managed to build MagnumImGui super easily. Therefore I will keep ImGui as an external dependency by default. Maybe adding a download script for people not using vcpkg.

**Comment by ShaddyDC** [comment]
Nice, I'd heard about the port, but I wasn't sure how well it's actually working.
Yeah, I completely agree with that option. Would you have someone compiling it enable that manually or do you think it would be best to already check in our CMakeLists.txt imgui library can't be found otherwise to install it manually? Like, automatically download it if neither find_package nor find_library can find it? That would be the most convenient to use, but I'm afraid it could be annoying in some cases if it just downloads more stuff just because a person has set some stuff up wrong. I guess you could add yet another option to only download it if that feature is enabled by a user, but then we're kinda back at sqare one, and I feel like it's starting to be over engineered.

**Comment by lecopivo** [comment]
Well I changed `find_library` to `find_package`, basically assuming you are using vcpkg. If you do not use vcpkg then I stole the cmake file from vcpkg to build imgui and added short instruction how to use it.

**Comment by lecopivo** [comment]
Yeah, doing it automatically from cmake would it be great. Can you detect if `find_package` fails and then automatically download and build a library?(that starts to sound like a package manager :D)

**Comment by ShaddyDC** [comment]
Yeah, you just have to leave out the REQUIRED. If it finds it, it'll set ` <package>_FOUND `. So if you just check something like `if(NOT imgui_FOUND)` and only then manage that stuff, you can probably make it work. :)

**Pull request merged**
